# Generated by Django 5.1.4 on 2025-03-08 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=255, upload_to='article_images/'),
            preserve_default=False,
        ),
    ]
