# Generated by Django 5.1.4 on 2025-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
