# Generated by Django 5.1.4 on 2025-03-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Health', 'Health'), ('Business', 'Business'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment')], default='Technology', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='article_images/'),
        ),
    ]
