# Generated by Django 5.1.4 on 2025-03-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-is_active', 'title'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ad was clicked'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='impressions',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ad was shown'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('top', 'Top Carousel'), ('inline', 'Between Articles'), ('bottom', 'Bottom Carousel'), ('main', 'Main Section')], default='main', help_text='Where this ad should appear on the page', max_length=10),
        ),
    ]
